language: generic

services:
  - docker

before_install:
  - docker build -t wcorderolara/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wcorderolara/docker-react npm run test -- --coverage
