version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: react-app-compose
    environment: 
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3200:3000"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app


